{
 "title": "China 2019-nCoV",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "区域",
    "query": "SHOW TAG VALUES ON \"ncov2019\" WITH KEY = \"region\""
   },
   {
    "name": "city",
    "label": "城市",
    "query": "SHOW TAG VALUES ON \"ncov2019\" WITH KEY = \"city\""
   }
  ]
 },
 "panels": [
  {
   "title": "全国疫情",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" }
     ],
     "measurement": "snapshots",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT count(\"confirmed\")  as \"$tag_city\" FROM \"snapshots\" WHERE $timeFilter GROUP BY  \"city\" ",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "实时报告",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "measurement": "events",
     "select": [
      [
       { "params": [ "summary" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "感染趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snapshots",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "确诊" ], "type": "alias" }
      ],
      [
       { "params": [ "suspect" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "疑似" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=~", "value": "/^$region$/" }
     ]
    }
   ]
  },
  {
   "title": "爬虫状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "scrapy_spiders",
     "select": [
      [
       { "params": [ "response_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "elapsed_time_in_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}